ARG CONTAINER_VERSION=ubuntu-20.04
FROM summerwind/actions-runner:${CONTAINER_VERSION}
USER root
RUN \
  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip" \
  unzip -q /tmp/awscliv2.zip -d /tmp \
  sudo /tmp/aws/install
USER runner
