on:
  workflow_dispatch:
  push:

env:
  REGISTRY: ghcr.io
  NAMESPACE: eric-zadara

jobs:
  identify:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    outputs:
      containers: "${{ steps.vars.outputs.containers }}"

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: identify containers to build
        id: vars
        run: |
          TODO=()
          echo "::group::Checking for versions files modified in '${GITHUB_SHA:-}'"
          for container in $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | awk -F'/' '/\/(versions|Dockerfile)$/{print $1}' | sort -u); do
            echo "Checking ${container}"
            if [[ -e "${container}/versions" ]]; then
              echo "Adding ${container}"
              TODO+=( "${container}" )
            fi
          done
          echo "::endgroup::"
          PAYLOAD=$(echo -n "${TODO[@]}" | tr ' ' '\n' | jq -c --raw-input -s 'split("\n")')
          echo "PAYLOAD - ${PAYLOAD}"
          echo "containers=${PAYLOAD}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: identify
    if: ${{ needs.identify.outputs.containers != '[]' && needs.identify.outputs.containers != '' }}
    strategy:
      fail-fast: false
      matrix:
        container: ${{ fromJSON(needs.identify.outputs.containers) }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: vars
        id: vars
        run: |
          VER=$(tail -n1 ${{ matrix.container }}/versions)
          echo "CONTAINER_VERSION=${VER}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ env.NAMESPACE }}/${{ matrix.container }}
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ steps.vars.outputs.CONTAINER_VERSION }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.vars.outputs.CONTAINER_VERSION }}
            type=semver,pattern={{major}},value=${{ steps.vars.outputs.CONTAINER_VERSION }}
            type=raw,${{ steps.vars.outputs.CONTAINER_VERSION }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.container }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args:
            CONTAINER_VERSION=${{ steps.vars.outputs.CONTAINER_VERSION }}

